export const CHECKPOINT_THEORY_LIBRARY_FALLBACK = [
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确题干关键词的拆解方法【理论方法】",
    "videoId": "1e6eaa05afcc8c25d7385d37441a1069_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-23/1753233827506.pdf",
    "analysisUrl": "",
    "noteText": "明确从题干中分析立意【理论方法】",
    "sourceSheet": "作文立意不准",
    "sourceRow": 2,
    "sortOrder": 59
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确题干关键词的拆解方法【作业讲解】",
    "videoId": "1e6eaa05afcca165b9138c6d3b190295_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-23/1753233827131.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-25/1753407111904.pdf",
    "noteText": "明确从题干中分析立意【作业讲解】",
    "sourceSheet": "作文立意不准",
    "sourceRow": 3,
    "sortOrder": 60
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确从材料中确定关键词的方法【理论方法】",
    "videoId": "1e6eaa05af6618a59acdac3231d50ff7_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-25/1753407110697.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 4,
    "sortOrder": 61
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确从材料中确定关键词的方法【作业讲解】",
    "videoId": "1e6eaa05affa8443842f0c603290b04c_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-25/1753424384984.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-25/1753407110055.pdf",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 5,
    "sortOrder": 62
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确关键词选择+整合到同一层级的方法【理论方法】",
    "videoId": "",
    "preClassUrl": "",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 6,
    "sortOrder": 63
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "关键词识别、判断和组合书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确关键词选择+整合到同一层级的方法【作业讲解】",
    "videoId": "",
    "preClassUrl": "",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 7,
    "sortOrder": 64
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "申论作文规则认知",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确掌握文体基本认识【理论方法】",
    "videoId": "1e6eaa05af5ec26bdc283cc26feb712d_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-16/1743822687057.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 8,
    "sortOrder": 65
  },
  {
    "checkpointName": "作文立意不准",
    "knowledgePoint": "申论作文规则认知",
    "knowledgeType": "required",
    "learningStatusRaw": "",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确掌握文体基本认识【作业讲解】",
    "videoId": "1e6eaa05af67029702a3c0e4affcd2f3_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-16/1744011595728.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-16/1744080226765.pdf",
    "noteText": "",
    "sourceSheet": "作文立意不准",
    "sourceRow": 9,
    "sortOrder": 66
  },
  {
    "checkpointName": "作文表达不畅",
    "knowledgePoint": "书面表达书写、判断方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确书面表达的方法+常见表达【理论方法】",
    "videoId": "1e6eaa05affa2dffebf7321392299bcb_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752571591389.pdf",
    "analysisUrl": "",
    "noteText": "明确文章语言如何优美——开头【理论课程】",
    "sourceSheet": "作文表达不畅",
    "sourceRow": 2,
    "sortOrder": 73
  },
  {
    "checkpointName": "作文表达不畅",
    "knowledgePoint": "书面表达书写、判断方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确书面表达的方法+常见表达【作业讲解】",
    "videoId": "1e6eaa05af3285c306ac83d15c90cfef_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752572490338.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-15/1752574194536.pdf",
    "noteText": "明确文章语言如何优美——开头【作业讲解】",
    "sourceSheet": "作文表达不畅",
    "sourceRow": 3,
    "sortOrder": 74
  },
  {
    "checkpointName": "作文表达不畅",
    "knowledgePoint": "书面表达书写、判断方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确文章语言如何优美——结尾【理论课程】",
    "videoId": "1e6eaa05afcb533e10715b333057cece_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752572029738.pdf",
    "analysisUrl": "",
    "noteText": "明确文章语言如何优美——结尾【理论课程】",
    "sourceSheet": "作文表达不畅",
    "sourceRow": 4,
    "sortOrder": 75
  },
  {
    "checkpointName": "作文表达不畅",
    "knowledgePoint": "书面表达书写、判断方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "http://img.yaotia.com/2025/07-25/1753427984311.pdf",
    "videoId": "1e6eaa05af93b67851849078191dab06_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752572490545.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-15/1752574194743.pdf",
    "noteText": "http://img.yaotia.com/2025/07-25/1753427984311.pdf",
    "sourceSheet": "作文表达不畅",
    "sourceRow": 5,
    "sortOrder": 76
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "作文论证规则认知+论证闭环书写、判定方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "明确论证形成闭环的前提条件【理论方法】",
    "videoId": "1e6eaa05af2e0e1fba3b74c3bc3b0caa_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752571631444.pdf",
    "analysisUrl": "",
    "noteText": "整个标准必学，都能被现有这两节课包含：明确论证思路【理论方法】；",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 2,
    "sortOrder": 67
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "作文论证规则认知+论证闭环书写、判定方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "明确论证形成闭环的前提条件【作业讲解】",
    "videoId": "1e6eaa05af6585eba6fe22be45882fc4_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-15/1752566181213.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-15/1752567377995.pdf",
    "noteText": "明确论证思路【作业讲解】",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 3,
    "sortOrder": 68
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "论据选择选择、书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "明确知道论据选择的方法+明确不同字数情况下论据的表达方式，能够书写出来【理论方法】",
    "videoId": "",
    "preClassUrl": "",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 4,
    "sortOrder": 69
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "论据选择选择、书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "明确知道论据选择的方法+明确不同字数情况下论据的表达方式，能够书写出来【作业讲解】",
    "videoId": "",
    "preClassUrl": "",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 5,
    "sortOrder": 70
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "论据选择选择、书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "明确论证力度加强的各类情形【理论方法】",
    "videoId": "",
    "preClassUrl": "",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 6,
    "sortOrder": 71
  },
  {
    "checkpointName": "作文逻辑不清",
    "knowledgePoint": "策论文如何书写",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、湖北、广东省份必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确策论文如何书写【理论方法】",
    "videoId": "1e6eaa05af31a2d2dc642ced811ef72a_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752055742339.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "作文逻辑不清",
    "sourceRow": 7,
    "sortOrder": 72
  },
  {
    "checkpointName": "公文结构不清",
    "knowledgePoint": "公文格式判定",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "根据题干分析格式【理论方法】",
    "videoId": "1e6eaa05afeddf8f7b99b8da3ee5094a_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-17/1750150070666.pdf",
    "analysisUrl": "",
    "noteText": "根据题干发文目的分析格式和答题逻辑【理论方法】",
    "sourceSheet": "公文结构不清",
    "sourceRow": 2,
    "sortOrder": 55
  },
  {
    "checkpointName": "公文结构不清",
    "knowledgePoint": "公文格式判定",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "根据题干分析格式【作业讲解】",
    "videoId": "1e6eaa05af9817b7e07bb62a9d55f5bd_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-17/1750150081253.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/06-17/1750150089505.pdf",
    "noteText": "根据题干发文目的分析格式和答题逻辑【作业讲解】",
    "sourceSheet": "公文结构不清",
    "sourceRow": 3,
    "sortOrder": 56
  },
  {
    "checkpointName": "公文结构不清",
    "knowledgePoint": "公文结构规则认知",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "近5年出现过的公文的格式要求+对应的书写方式【理论方法】",
    "videoId": "1e6eaa05af3347eaa36f3013bdcc7cdb_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-03/1743674266920.pdf",
    "analysisUrl": "",
    "noteText": "认识公文格式【理论方法】",
    "sourceSheet": "公文结构不清",
    "sourceRow": 11,
    "sortOrder": 57
  },
  {
    "checkpointName": "公文结构不清",
    "knowledgePoint": "公文结构规则认知",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "近5年出现过的公文的格式要求+对应的书写方式【作业讲解】",
    "videoId": "1e6eaa05af98222c1a4015f159e8c430_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-03/1743674766780.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-16/1743674515132.pdf",
    "noteText": "http://img.yaotia.com/2025/04-25/1745574249150.pdf",
    "sourceSheet": "公文结构不清",
    "sourceRow": 12,
    "sortOrder": 58
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "解释型分析的判定方法+开头写法【理论方法】",
    "videoId": "1e6eaa05af5f94b166f05e296faf1176_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-25/1750855151431.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论不是这么拆的，但是可以让学员暂时现学：明确解释词语的分析题如何答【理论方法】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 2,
    "sortOrder": 39
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "解释型分析的判定方法+开头写法【作业讲解】",
    "videoId": "1e6eaa05af4fe614558d350f3352c6d5_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-25/1756087983395.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/08-25/1756087983680.pdf",
    "noteText": "明确解释词语的分析题如何答【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 3,
    "sortOrder": 40
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "解释型分析结尾的判断方法+书写方法【理论方法】",
    "videoId": "1e6eaa05af3aa8bd526303406fa798c4_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-25/1750855192926.pdf",
    "analysisUrl": "",
    "noteText": "明确解释句子的分析题如何答【理论方法】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 4,
    "sortOrder": 41
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "解释型分析结尾的判断方法+书写方法【作业讲解】",
    "videoId": "1e6eaa05af74512c77a9a0c45bbcf827_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-25/1750855263744.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/06-25/1750855625261.pdf",
    "noteText": "明确解释句子的分析题如何答【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 5,
    "sortOrder": 42
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "掌握题干分类依据、规则+方法【理论方法】",
    "videoId": "1e6eaa05af06ea74abd5aa846bce9fb4_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-24/1756027036814.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确解释型分析答题框架【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 6,
    "sortOrder": 43
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "解释型分析必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "掌握题干分类依据、规则+方法【作业讲解】",
    "videoId": "1e6eaa05af4e961432a7c16882b094b0_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-24/1756027256284.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/08-24/1756023739622.pdf",
    "noteText": "明确解释型分析答题框架【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 7,
    "sortOrder": 44
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "评价型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、国考、广东、吉林、北京、江苏、河南省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "评价型分析的判定方法+开头写法【理论方法】和评价型分析的判定方法+开头写法【作业讲解】",
    "videoId": "1e6eaa05af6cf4a468741d9041092698_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752042457512.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确评价型分析答题框架【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 8,
    "sortOrder": 45
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "评价型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、国考、广东、吉林、北京、江苏、河南省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确评价型分析答题框架【作业讲解】",
    "videoId": "1e6eaa05afd004b5c04dbd942aa34b81_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752042140791.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752042180160.pdf",
    "noteText": "明确评价型分析答题框架【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 9,
    "sortOrder": 46
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "评价型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、国考、广东、吉林、北京、江苏、河南省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "现有知识理论叫做：明确评价型分析如何答【理论方法】；",
    "videoId": "1e6eaa05afab70066807bfbbe063b378_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752044443074.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确评价型分析如何答【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 10,
    "sortOrder": 47
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "评价型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、国考、广东、吉林、北京、江苏、河南省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确评价型分析答题如何答【作业讲解】",
    "videoId": "1e6eaa05aff74d68eeb743738b95e01f_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752044444982.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752044442782.pdf",
    "noteText": "明确评价型分析答题如何答【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 11,
    "sortOrder": 48
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "比较型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "比较型分析的判定方法+开头写法【理论方法】和比较型分析的判定方法+开头写法【作业讲解】",
    "videoId": "1e6eaa05afb4289f355d18f7f7fb0c2e_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752041343207.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确比较型分析答题框架【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 12,
    "sortOrder": 49
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "比较型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确比较型分析答题框架【作业讲解】",
    "videoId": "1e6eaa05afa1295e56b673f546472d02_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752041583380.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752033386825.pdf",
    "noteText": "明确比较型分析答题框架【作业讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 13,
    "sortOrder": 50
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "比较型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "现有知识理论叫做：明确比较型分析如何答【理论方法】；",
    "videoId": "1e6eaa05afab70066807bfbbe063b378_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752044443074.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确比较型分析如何答【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 14,
    "sortOrder": 51
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "比较型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确比较型分析如何答【作业讲解】；",
    "videoId": "1e6eaa05afa1295e56b673f546472d02_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752044444982.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752033386825.pdf",
    "noteText": "明确比较型分析如何答【作业讲解】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 15,
    "sortOrder": 52
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "混合型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "混合型分析的判定方法+开头写法【理论方法】和混合型分析的判定方法+开头写法【作业讲解】",
    "videoId": "1e6eaa05afa282aa5dedebf66e94c762_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752031121857.pdf",
    "analysisUrl": "",
    "noteText": "现有知识理论叫做：明确混合型分析如何答【理论方法】；",
    "sourceSheet": "分析结构不清",
    "sourceRow": 16,
    "sortOrder": 53
  },
  {
    "checkpointName": "分析结构不清",
    "knowledgePoint": "混合型必要组成部分判定和书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏省份必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "明确混合型分析如何答【方法讲解】",
    "videoId": "1e6eaa05af1d49a34e90db71d9c3318e_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-09/1752031123812.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752031121398.pdf",
    "noteText": "明确混合型分析如何答【方法讲解】",
    "sourceSheet": "分析结构不清",
    "sourceRow": 17,
    "sortOrder": 54
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导依据的识别、判定",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确对策从哪找【理论方法】",
    "videoId": "1e6eaa05af25de6fbda641e79cb3964f_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-27/1747659535558.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 2,
    "sortOrder": 31
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导依据的识别、判定",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确对策从哪找【作业讲解】",
    "videoId": "1e6eaa05af12cec62c1805be118ebd47_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-03/1751521547522.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/06-29/1751186563847.pdf",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 3,
    "sortOrder": 32
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导方法+书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确分析推导对策【理论方法】",
    "videoId": "1e6eaa05af9649aaaddc3c9d54643d29_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-23/1753244564670.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 4,
    "sortOrder": 33
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导方法+书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确分析推导对策【作业讲解】",
    "videoId": "1e6eaa05aff63a80c054c60c38abd00b_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-16/1752630777466.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/05-27/1748317997456.pdf",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 5,
    "sortOrder": 34
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导方法+书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "广东必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确对策顺序如何判定和书写【理论方法】",
    "videoId": "1e6eaa05afc2a0b6a4a7e92eee2557bd_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-28/1748399058823.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 6,
    "sortOrder": 35
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策推导方法+书写方法",
    "knowledgeType": "required",
    "learningStatusRaw": "广东必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确对策顺序如何判定和书写【作业讲解】",
    "videoId": "1e6eaa05afd0f7a2d00b559b368ecdcf_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-28/1748399114004.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/05-28/1748399225409.pdf",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 7,
    "sortOrder": 36
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策书写规则认知、判定",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确判断对应性、针对性、可操作性、可行性要求的方法【理论方法】",
    "videoId": "1e6eaa05afeb95ae5c8d458368a34673_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-05/1754384332764.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 8,
    "sortOrder": 37
  },
  {
    "checkpointName": "对策推导困难",
    "knowledgePoint": "对策书写规则认知、判定",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确判断对应性、针对性、可操作性、可行性要求的方法【理论方法】",
    "videoId": "1e6eaa05af50ab1747eb8dbb1c4090fc_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-03/1743673559676.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-16/1743909395004.pdf",
    "noteText": "",
    "sourceSheet": "对策推导困难",
    "sourceRow": 9,
    "sortOrder": 38
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "抽象总结材料信息",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有待修改",
    "theoryTitle": "如何总结每一句的主要信息+分析句子间主要信息的共性=得出本段的主旨【理论方法】",
    "videoId": "1e6eaa05afda14e9982e5b45bc866839_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-19/1750333984392.pdf",
    "analysisUrl": "",
    "noteText": "如何提炼准确【理论方法】",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 2,
    "sortOrder": 18
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "规范转述材料信息",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "根据本段的主旨匹配规范表述的短语或词语进行精准描述形成前置词、关键词【理论方法】",
    "videoId": "1e6eaa05aff84910cdcf6f292bd14f3d_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-25/1745479816821.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 6,
    "sortOrder": 19
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "规范转述材料信息",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "根据本段的主旨匹配规范表述的短语或词语进行精准描述形成前置词、关键词【作业讲解】",
    "videoId": "1e6eaa05afd6c5e7986b5175048ec4e6_1",
    "preClassUrl": "http://img.yaotia.com/2025/06-20/1750389263053.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/08-11/1754907137664.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 7,
    "sortOrder": 20
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性（一）【理论方法】",
    "videoId": "1e6eaa05af6b614ddc8754621046f9a3_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-20/1747725538106.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 8,
    "sortOrder": 21
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性（一）【作业讲解】",
    "videoId": "1e6eaa05af6a761d3ea98b464838ee3b_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-18/1755505780651.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-09/1752046621260.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 9,
    "sortOrder": 22
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性之（二）【理论方法】",
    "videoId": "1e6eaa05af9e5370bedf6b2b5d60575e_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1745459988949.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 10,
    "sortOrder": 23
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性（二）【作业讲解】",
    "videoId": "1e6eaa05afacd21c368e149c500f7e8c_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1745479940711.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-03/1751526446904.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 11,
    "sortOrder": 24
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "安徽；黑龙江；江西；辽宁；青海；国考、河北、湖北、内蒙古必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性之变化类【理论方法】",
    "videoId": "1e6eaa05af5b425691eae7294ff9328a_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1747106118272.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 16,
    "sortOrder": 25
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "安徽；黑龙江；江西；辽宁；青海；国考、河北、湖北、内蒙古必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性之变化类【作业讲解】",
    "videoId": "1e6eaa05afae47825acf7ffa2edd2ce5_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1747105853619.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/05-13/1747105939701.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 17,
    "sortOrder": 26
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "安徽；重庆；黑龙江；江西；辽宁；内蒙古；山西；陕西；上海、湖北、广东、深圳、浙江、山东、广西、河南",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性之特点亮点【理论方法】",
    "videoId": "1e6eaa05af306e4cbedca9f3472b1137_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1747105112849.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 18,
    "sortOrder": 27
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "required",
    "learningStatusRaw": "安徽；重庆；黑龙江；江西；辽宁；内蒙古；山西；陕西；上海、湖北、广东、深圳、浙江、山东、广西、河南",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性之特点亮点【作业讲解】",
    "videoId": "1e6eaa05af5702a70bb55ca5ccbd660e_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-13/1747105171649.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/05-13/1747105254849.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 19,
    "sortOrder": 28
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "正确的申论阅读规则意识",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断、题干和材料中关于主体、主题的信息【理论方法】",
    "videoId": "1e6eaa05afb537864beba865063f1ad3_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-01/1743493672441.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 21,
    "sortOrder": 29
  },
  {
    "checkpointName": "提炼转述困难",
    "knowledgePoint": "正确的申论阅读规则意识",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断、题干和材料中关于主体、主题的信息【理论方法】",
    "videoId": "1e6eaa05af4c906691ef914572dc8309_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-16/1743665169022.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-10/1743665213152.pdf",
    "noteText": "",
    "sourceSheet": "提炼转述困难",
    "sourceRow": 22,
    "sortOrder": 30
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "分析材料逻辑关系判断主次信息",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断材料信息主次关系【理论方法】",
    "videoId": "1e6eaa05af091f40ad95491deac4eab2_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-18/1744944794145.pdf",
    "analysisUrl": "",
    "noteText": "明确前置词书写的方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 2,
    "sortOrder": 1
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "分析材料逻辑关系判断主次信息",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断材料信息主次关系【作业讲解】",
    "videoId": "1e6eaa05af3109303c51b219d82925da_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-02/1743400149927.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-02/1743400150179.pdf",
    "noteText": "明确前置词书写的方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 4,
    "sortOrder": 2
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "材料信息取舍规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "划分材料层级+根据层级取舍+规划要点字数【理论方法】",
    "videoId": "1e6eaa05aff96b0c3aa7b952fb472023_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-02/1743563075032.pdf",
    "analysisUrl": "",
    "noteText": "明确要点取舍的方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 7,
    "sortOrder": 3
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "材料信息取舍规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "划分材料层级+根据层级取舍+规划要点字数【作业讲解】",
    "videoId": "1e6eaa05afe563f593cb6cfb7f94550c_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-02/1743400152668.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-02/1743400152800.pdf",
    "noteText": "明确要点取舍的方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 8,
    "sortOrder": 4
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "要点分类判定规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "掌握材料分类依据、规则+方法【理论方法】和掌握材料分类依据、规则+方法【作业讲解】",
    "videoId": "1e6eaa05af3ba3052b803ed867a9a2be_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-18/1744978651175.pdf",
    "analysisUrl": "",
    "noteText": "掌握材料通用分类依据、规则+方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 9,
    "sortOrder": 5
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "要点分类判定规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "掌握材料通用分类依据、规则+方法（作业讲解）",
    "videoId": "1e6eaa05af29f558eeff4fa6664cb748_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-17/1744880274099.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-24/1745477378833.pdf",
    "noteText": "掌握材料通用分类依据、规则+方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 10,
    "sortOrder": 6
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "要点分类判定规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "掌握材料特殊分类依据、规则+方（理论方法）",
    "videoId": "1e6eaa05af963eeddafef96edc462c9e_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-18/1744978745838.pdf",
    "analysisUrl": "",
    "noteText": "掌握材料特殊分类依据、规则+方（理论方法）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 11,
    "sortOrder": 7
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "要点分类判定规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "掌握材料特殊分类依据、规则+方法（作业讲解）",
    "videoId": "1e6eaa05af57ef5d73d50da46e0d2041_1",
    "preClassUrl": "http://img.yaotia.com/2025/08-14/1755141775109.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/08-14/1755141941520.pdf",
    "noteText": "掌握材料特殊分类依据、规则+方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 12,
    "sortOrder": 8
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "总括句识别、书写规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "判断段落间的总分关系+定位总结性的信息【理论方法】",
    "videoId": "1e6eaa05afbbf5ad528f8dba54c62569_1",
    "preClassUrl": "http://img.yaotia.com/2025/05-27/1748320831216.pdf",
    "analysisUrl": "",
    "noteText": "掌握作答书写逻辑方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 13,
    "sortOrder": 9
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "总括句识别、书写规则",
    "knowledgeType": "required",
    "learningStatusRaw": "必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "判断段落间的总分关系+定位总结性的信息【理论方法】",
    "videoId": "1e6eaa05af7007830ffab806186ca3d0_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-25/1745377304850.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-25/1745378250371.pdf",
    "noteText": "掌握作答书写逻辑方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 14,
    "sortOrder": 10
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "答案要点书写规则",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、北京省份必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "一段话式书写规则【理论方法】",
    "videoId": "1e6eaa05af731dab2226fbee98ef6440_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-08/1751968681702.pdf",
    "analysisUrl": "",
    "noteText": "明确一段话式题目如何作答的方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 16,
    "sortOrder": 11
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "答案要点书写规则",
    "knowledgeType": "required",
    "learningStatusRaw": "江苏、北京省份必学",
    "provinceTags": [],
    "courseStatus": "已有但需要修改",
    "theoryTitle": "一段话式书写规则【作业讲解】",
    "videoId": "1e6eaa05afaa5ee14d125cfb57d47191_1",
    "preClassUrl": "http://img.yaotia.com/2025/07-08/1751968681316.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/07-08/1751970757087.pdf",
    "noteText": "明确一段话式题目如何作答的方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 17,
    "sortOrder": 12
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "正确的申论阅读规则意识",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断、题干和材料中关于主体、主题的信息【理论方法】",
    "videoId": "1e6eaa05afb537864beba865063f1ad3_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-01/1743493672441.pdf",
    "analysisUrl": "",
    "noteText": "判断、题干和材料中关于主体、主题的信息的方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 20,
    "sortOrder": 13
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "正确的申论阅读规则意识",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断、题干和材料中关于主体、主题的信息【理论方法】",
    "videoId": "1e6eaa05af4c906691ef914572dc8309_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-16/1743665169022.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-10/1743665213152.pdf",
    "noteText": "判断、题干和材料中关于主体、主题的信息的方法（作业讲解）",
    "sourceSheet": "要点不全不准",
    "sourceRow": 21,
    "sortOrder": 14
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性，学会寻找要点的方法【理论方法】",
    "videoId": "1e6eaa05af3e219ececff428b834bfec_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-18/1744978559304.pdf",
    "analysisUrl": "",
    "noteText": "",
    "sourceSheet": "要点不全不准",
    "sourceRow": 22,
    "sortOrder": 15
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "申论各作答要素识别与书写",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "判断题干+材料要素一致性，学会寻找要点的方法【作业讲解】",
    "videoId": "1e6eaa05af16261b021b9dafbaf9214c_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-17/1744880978056.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/04-27/1745725412821.pdf",
    "noteText": "",
    "sourceSheet": "要点不全不准",
    "sourceRow": 23,
    "sortOrder": 16
  },
  {
    "checkpointName": "要点不全不准",
    "knowledgePoint": "明确前置词的作用",
    "knowledgeType": "optional",
    "learningStatusRaw": "选学",
    "provinceTags": [],
    "courseStatus": "已有",
    "theoryTitle": "明确前置词识别的方法",
    "videoId": "1e6eaa05af9afcbf84c0551c79c293f5_1",
    "preClassUrl": "http://img.yaotia.com/2025/04-02/1743563076755.pdf",
    "analysisUrl": "http://img.yaotia.com/2025/08-14/1755141941520.pdf",
    "noteText": "明确前置词识别的方法",
    "sourceSheet": "要点不全不准",
    "sourceRow": 24,
    "sortOrder": 17
  }
] as const
